//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string DateOfBirth { get; set; }
        public string Experience { get; set; }
        public string gender { get; set; }
        public string address { get; set; }
    }
}
